### ISSUE TITLE
Pressure value differs depending on read frequency

### ISSUE THREAD

**Issue by AcuarioCat** [fanfanlatulipe26/XGZP6897D#4]
Hi,
I am reading a sensor but the pressure value changes substantially depending on the frequency I read the sensor.
If I read at roughly 10mS I get 2.05Pa, 50mS I get -5.2Pa, at 100mS -22Pa, at 500 and above mS -34Pa
The temperature also varies, at 10mS 26C, at 50mS 25.5C
The sensor is not connected to anything that would give a pressure difference.
I'm using the +-2500 version with K set to 2048

I'm using an ESP32 with the latest Arduino code.

**Comment by fanfanlatulipe26** [comment]
I tried the XGZP6897D\_demo at full speed  (whitout any delay in the loop, writing on Serial at 115200bds) and the results are the same  as the one we have with a delay(1000) in the loop. 

Any how the library is always waiting for the completion of a conversion.

Do you have a 100nF capacitor between VCC ang GND, just on top of the chip (very short wires): it makes a **BIG difference** in the reading.  See the "Circuit Diagram" in the middle of the Datasheet (page 3 & 4 )

My configuration: ESP32 Dev Kit V1, ESP32 software 2.0.14

XGZP6897D -1000/1000

Keep me informed

**Comment by fanfanlatulipe26** [comment]
is it still an issue for you ?

**Comment by AcuarioCat** [comment]
I have just got back to it. It seems there is a minimum time of approximately 30mS between reads to obtain consistent results. Any faster and the results are not reliable.

From my point of view it is a limitation in the sensor, not your code as you are only returning a result on the correct setting of the data available flag.

You can see the effect if you run the following code. The results are inconsistent below approximately 30.

`    while (1) {
        bool b = aisSensor.readSensor(temperature, pressure);
        Serial.printf("C:%d T:%.2fC P:%.2fPa\n", count, temperature, pressure);
        if (count < 10)
        {
            vTaskDelay(pdTICKS_TO_MS(5));
        }
        else if (count < 20)
        {
            vTaskDelay(pdTICKS_TO_MS(10));
        }
        else if (count < 30)
        {
            vTaskDelay(pdTICKS_TO_MS(20));
        }
        else if (count < 40)
        {
            vTaskDelay(pdTICKS_TO_MS(30));
        }
        else if (count < 50)
        {
            vTaskDelay(pdTICKS_TO_MS(40));
        }
        else if (count < 60)
        {
            vTaskDelay(pdTICKS_TO_MS(50));
        }
        else 
            vTaskDelay(pdTICKS_TO_MS(5));
        count++;
    }
`

**Comment by fanfanlatulipe26** [comment]
I adapted your code and don't see significant changes in the outputs.       
I also made a test  with 0 wait, 10ms,20ms ....  taking 20 samples each time and computing the Min, Max and Average for pressure and temperature.     
Results are consistent.      
Repeatability and accuracy seem not too bad at least when same pressure is applied on both inputs.     
It seems that the pressure does not depend at all on the wait time, but on the other hand the temperature Tmax and TAvr are always higher when the wait time is small: in my opinion it is OK because the sensor is more active.      
Maybe your device is defective ?      
My setup:    
XGZP6897D for the range -1000 to +1000 Pa (K = 4096)    
ESP32 Dev Kit V1 powered by USB from the PC    
Sensor powered from the 3.3v output of the ESP32 bord.     
Here are my results:  

```
wait:0	Pmin:16.59 Pmax:18.29 Pavr:17.41 Tmin:23.61 Tmax:24.47 Tavr:24.15
wait:10	Pmin:16.60 Pmax:18.43 Pavr:17.53 Tmin:24.12 Tmax:24.49 Tavr:24.19
wait:20	Pmin:16.63 Pmax:18.32 Pavr:17.49 Tmin:23.89 Tmax:24.11 Tavr:23.95
wait:30	Pmin:16.55 Pmax:18.07 Pavr:17.33 Tmin:23.77 Tmax:23.89 Tavr:23.80
wait:40	Pmin:16.40 Pmax:17.93 Pavr:17.22 Tmin:23.69 Tmax:23.77 Tavr:23.71
wait:50	Pmin:16.74 Pmax:18.14 Pavr:17.35 Tmin:23.64 Tmax:23.70 Tavr:23.65
wait:60	Pmin:16.56 Pmax:18.23 Pavr:17.34 Tmin:23.59 Tmax:23.64 Tavr:23.61

wait:0	Pmin:16.56 Pmax:18.32 Pavr:17.40 Tmin:23.60 Tmax:24.47 Tavr:24.14
wait:10	Pmin:16.93 Pmax:18.27 Pavr:17.52 Tmin:24.11 Tmax:24.47 Tavr:24.19
wait:20	Pmin:17.02 Pmax:18.41 Pavr:17.58 Tmin:23.89 Tmax:24.12 Tavr:23.94
wait:30	Pmin:16.72 Pmax:18.28 Pavr:17.49 Tmin:23.75 Tmax:23.89 Tavr:23.80
wait:40	Pmin:16.66 Pmax:18.35 Pavr:17.42 Tmin:23.68 Tmax:23.76 Tavr:23.71
wait:50	Pmin:16.34 Pmax:18.27 Pavr:17.33 Tmin:23.62 Tmax:23.69 Tavr:23.64
wait:60	Pmin:14.90 Pmax:20.88 Pavr:17.42 Tmin:23.58 Tmax:23.63 Tavr:23.60

wait:0	Pmin:16.63 Pmax:18.17 Pavr:17.36 Tmin:23.60 Tmax:24.47 Tavr:24.13
wait:10	Pmin:16.84 Pmax:18.33 Pavr:17.51 Tmin:24.11 Tmax:24.47 Tavr:24.18
wait:20	Pmin:16.86 Pmax:18.46 Pavr:17.59 Tmin:23.88 Tmax:24.12 Tavr:23.94
wait:30	Pmin:16.64 Pmax:18.40 Pavr:17.44 Tmin:23.75 Tmax:23.89 Tavr:23.79
wait:40	Pmin:16.54 Pmax:18.13 Pavr:17.37 Tmin:23.68 Tmax:23.75 Tavr:23.70
wait:50	Pmin:16.46 Pmax:18.14 Pavr:17.27 Tmin:23.62 Tmax:23.68 Tavr:23.64
wait:60	Pmin:16.46 Pmax:17.78 Pavr:17.19 Tmin:23.58 Tmax:23.63 Tavr:23.59

```

**Comment by AcuarioCat** [comment]
I duplicated your test - maybe I have a faulty sensor, I have another one I can try.
Mine is for -2500 to +2500 with K=2048
The temperature results seem consistent with yours but pressure is a mess
wait:0 Pmin:-50.33 Pmax:-17.14 Pavr:-23.53 Tmin:25.64 Tmax:26.14 Tavr:25.92
wait:10 Pmin:-17.11 Pmax:-12.41 Pavr:-14.10 Tmin:26.14 Tmax:26.21 Tavr:26.17
wait:20 Pmin:-14.02 Pmax:-12.44 Pavr:-13.33 Tmin:26.13 Tmax:26.23 Tavr:26.17
wait:30 Pmin:-14.98 Pmax:-12.51 Pavr:-14.33 Tmin:26.05 Tmax:26.14 Tavr:26.09
wait:40 Pmin:-17.69 Pmax:-15.06 Pavr:-16.52 Tmin:25.97 Tmax:26.07 Tavr:26.02
wait:50 Pmin:-19.16 Pmax:-16.90 Pavr:-18.43 Tmin:25.93 Tmax:26.00 Tavr:25.96
wait:60 Pmin:-21.98 Pmax:-19.04 Pavr:-20.85 Tmin:25.89 Tmax:25.94 Tavr:25.91

**Comment by fanfanlatulipe26** [comment]
Forgot to say that I have a 100nF capacitor between VCC and GND on top of the chip with very short wires.
Hope it helps

**Comment by AcuarioCat** [comment]
Yes, I have the same

**Comment by AcuarioCat** [comment]
I have a bad sensor :-( 
I connected the other sensor I have and the results are good :-)
`
wait:0 Pmin:12.89 Pmax:13.27 Pavr:13.04 Tmin:25.73 Tmax:26.25 Tavr:26.02
wait:10 Pmin:12.73 Pmax:13.19 Pavr:13.05 Tmin:26.23 Tmax:26.32 Tavr:26.27
wait:20 Pmin:12.75 Pmax:13.29 Pavr:13.10 Tmin:26.23 Tmax:26.32 Tavr:26.27
wait:30 Pmin:12.96 Pmax:13.44 Pavr:13.21 Tmin:26.16 Tmax:26.25 Tavr:26.20
wait:40 Pmin:12.94 Pmax:13.38 Pavr:13.12 Tmin:26.11 Tmax:26.16 Tavr:26.13
wait:50 Pmin:13.02 Pmax:13.34 Pavr:13.16 Tmin:26.04 Tmax:26.12 Tavr:26.07
wait:60 Pmin:13.02 Pmax:13.50 Pavr:13.16 Tmin:26.00 Tmax:26.05 Tavr:26.03
`
