### ISSUE TITLE
Make call to readSensor non blocking

### ISSUE THREAD

**Issue by AcuarioCat** [fanfanlatulipe26/XGZP6897D#5]
The current call to readSensor is blocking as it calls readRawSensor and then waits indefinitely for bit 3 of 0x03 to be set.
If this never occurs the call will block waiting for something that may never happen.

Suggestion:
- Change both readSensor and readRawSensor to return boolean true/false on success.
in readSensor:

    if(!readRawSensor(rawTemperature,rawPressure))
        return false;
.
.
  return true;

- Add a timeout retry loop in readRawSensor:
 
// wait until the end of conversion (Sco bit in CMD_reg. bit 3)
  uint8_t retryCount = 0;           //So it doesn´t block..
  do {
      retryCount++;
      if (retryCount == 20)
          return false;             //Read failed

    _Wire->beginTransmission(_I2C_address);
    _Wire->write(0x30);                       //send 0x30 CMD register address
    _Wire->endTransmission();
    _Wire->requestFrom(_I2C_address, byte(1));
    CMD_reg = _Wire->read();                //read 0x30 register value
    Serial.println("Wait");  
} while ((CMD_reg & 0x08) > 0);        //loop while bit 3 of 0x30 register copy is 1

**Comment by fanfanlatulipe26** [comment]
Interesting. 
But if the device is failing, the begin() should already return "false" and we can test it.
Did you experimente issues when reading after a successfull initialization with begin() ?. Do you have a testcase / setup ?

This simple library assumes that after a successfull begin, the device will be OK for subsequent reads.

**Comment by AcuarioCat** [comment]
I always look at various test cases. As the begin is only called once but reading happens maybe 1000´s of times I like to cater for the possibility of a sensor failure, and that this will not compromise a system.

In my actual scenario I am running the sensor in an RTOS task. The I2C bus is shared with other devices running in other tasks.
Access to the I2C bus is using a mutex semaphore that is taken before a sensor is read and released after the sensor is read.
If a sensor blocks for whatever reason the whole system will stop as the failed device will have the i2c bus semaphore and will never release it.

The device I am designing is for use in a moving vehicle so there are various possibilities for failure, a power glitch, vibration causing a connection to the device to fail, mechanical shock. I can handle a sensor failure if I know it has failed but not if it effectively blocks the other sensors from being read.

I also think it is good practice not to block execution of a program due to a single failure of a device.
I have modified the copy of the library that I have so it is no longer blocking, I have posted my changes if you want to incorporate them.

**Comment by fanfanlatulipe26** [comment]
I made some tests, trying to simulate a failing sensor (removing VCC , removing SDA or SCA).
 Running on ESP32 release 2.0.14.  

With your solution, in case of timeout, the readSensor returns after more or less 20s. There is some 1000ms timeout internal in the wire library for the sequence beginTransmission/write/endTransmission/requestFrom/read  and as we do the loop 20 times we get 20s ....  
Of course it should be less if the pressure sensor exhibits a gentle breakdown,  not mangling I2C bus, just killing bit 3 in the status register.  

With my solution (test on millis(), with a 20ms desired timeout) we catch the timeout at the return of readSensor after only 1s ... Nevertheless it is a lot for a moving vehicule....  

It seems that Arduino people are improving some timeout management in the Wire library,  but it is not clear for me if it is already available and on which platforms. (last update of the doc is very new 20/11/2024)
setWireTimeout()
clearWireTimeoutFlag()
getWireTimeoutFlag()  

Better to wait ??

**Comment by fanfanlatulipe26** [comment]
You also have the XGZP6897A with a simple analog output. No I2C bus burden, but need an analog input.

**Comment by AcuarioCat** [comment]
> I made some tests, trying to simulate a failing sensor (removing VCC , removing SDA or SCA). Running on ESP32 release 2.0.14.
> 
> With your solution, in case of timeout, the readSensor returns after more or less 20s. There is some 1000ms timeout internal in the wire library for the sequence beginTransmission/write/endTransmission/requestFrom/read and as we do the loop 20 times we get 20s .... Of course it should be less if the pressure sensor exhibits a gentle breakdown, not mangling I2C bus, just killing bit 3 in the status register.
> 
> With my solution (test on millis(), with a 20ms desired timeout) we catch the timeout at the return of readSensor after only 1s ... Nevertheless it is a lot for a moving vehicule....
> 
> It seems that Arduino people are improving some timeout management in the Wire library, but it is not clear for me if it is already available and on which platforms. (last update of the doc is very new 20/11/2024) setWireTimeout() clearWireTimeoutFlag() getWireTimeoutFlag()
> 
> Better to wait ??

Interesting, I must admit I have not yet tried simulating failures, only analysing code to see where the potential problems are. 
I´ll let you know when I do run simulations. 
I still need to check that the output is consistent as per my other issue. I have been busy with other parts of the design so haven´t revisited that yet.

**Comment by fanfanlatulipe26** [comment]
I prepared a new version 1.0.3, non blocking call, with return code.    
If you want to have a look it is in a development branch [dev-1.0.3](https://github.com/fanfanlatulipe26/XGZP6897D/tree/dev-1.0.3)
All the files are updated, but not yet released.    
Thank you for your help.

**Comment by AcuarioCat** [comment]
Works great, unplugging the sensor returns false and no blocking.
Great job!

**Comment by fanfanlatulipe26** [comment]
Thank. I publish the release.  

The behavior depends a bit on the platform/core release. Seems OK  for ESP32 3.1.2, but not so good on ESP8266 or with core 2.0.14, or on RP2040when I just unplug VCC.
